name: runner

on:
  workflow_dispatch:

env:
  PULL_TOKEN: ${{ secrets.PULL_TOKEN }}

jobs:
  build:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run test script
        working-directory: $HOME/Documents/pmo/pmo-api
        run: |
          git pull https://${{ env.PULL_TOKEN }}@github.com/Sathyanarayanan-Dhanuskodi/runner-test.git
